# Generated by Django 3.0 on 2020-02-17 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gsm_rf_device', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(default=0.0)),
                ('lng', models.FloatField(default=0.0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gsm_rf_device.GsmDevice')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RequestCancellation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canceled_by', models.CharField(max_length=20)),
                ('cancellation_reason', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='signal_reciever.Events')),
            ],
            options={
                'db_table': 'request_cancellation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EventHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(default=0.0)),
                ('lng', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='signal_reciever.Events')),
            ],
            options={
                'db_table': 'event_history',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='requestcancellation',
            index=models.Index(fields=['event_id', 'canceled_by'], name='request_can_event_i_8ef2ef_idx'),
        ),
        migrations.AddIndex(
            model_name='events',
            index=models.Index(fields=['device_id', 'user_id'], name='events_device__1e3583_idx'),
        ),
        migrations.AddIndex(
            model_name='eventhistory',
            index=models.Index(fields=['event_id'], name='event_histo_event_i_bd602d_idx'),
        ),
    ]
