# Generated by Django 3.0 on 2020-02-17 20:32

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acs_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GsmDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radio_freq_reciever', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acs_users.IpWhitelist')),
            ],
            options={
                'db_table': 'gsm_device',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RfDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(default=0.0)),
                ('lng', models.FloatField(default=0.0)),
                ('locality_density', models.IntegerField(default=0)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='en', max_length=5, null=True), blank=True, null=True, size=None)),
                ('radius', models.FloatField(default=0.0)),
                ('webhook_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsm_rf_device.GsmDevice')),
            ],
            options={
                'db_table': 'rf_device',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='rfdevice',
            index=models.Index(fields=['device_id', 'lat', 'lng', 'radius'], name='rf_device_device__51f4a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rfdevice',
            unique_together={('device_id',)},
        ),
        migrations.AddIndex(
            model_name='gsmdevice',
            index=models.Index(fields=['ip'], name='gsm_device_ip_id_b8947b_idx'),
        ),
    ]
