# Generated by Django 3.0 on 2020-02-17 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('lat', models.FloatField(default=0.0)),
                ('lng', models.FloatField(default=0.0)),
                ('language', models.CharField(blank=True, default='en', max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'police_station',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=300, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('police_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='police_station.PoliceStation')),
            ],
            options={
                'db_table': 'postal_code',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='policestation',
            index=models.Index(fields=['lat', 'lng', 'name'], name='police_stat_lat_e2fb6e_idx'),
        ),
        migrations.AddIndex(
            model_name='postalcode',
            index=models.Index(fields=['postal_code', 'police_station'], name='postal_code_postal__7ddf5e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postalcode',
            unique_together={('postal_code', 'police_station')},
        ),
    ]
